SRC=$(wildcard ./*.c)
OBJ=$(patsubst %.c, %.o, $(SRC))
BIN=./main

DSRC=$(wildcard ../dynamic/*.c)
DOBJ=$(patsubst %.c, %.o, $(DSRC))
DBIN= ../dynamic/libdynamic_test.so

all:$(DBIN) $(BIN) 
$(BIN):$(OBJ)
	gcc $^ -o $@ -L../dynamic -ldynamic_test -L../static -lstatic_test
%.o:%.c
	gcc -o $@ -c $<
$(DBIN):$(DOBJ)
	gcc $^ -o $@  --share
$(DOBJ):$(DSRC)
	gcc -o $@ -c $< -fPIC


.PHONY:clean
clean:
	rm -r $(BIN) $(OBJ)
