#------------------------------配置区域----------------------------

DIR=./static

#静态库名以lib为前缀，.a为后缀
BIN=$(DIR)/libstatic_test.a

SHARE=--share

CFLAG= -Wall -I./inc

LFLAG=

CC=gcc -o

AR=ar -cr

#编译静态库用ar -cr命令
CO=$(AR)
#-------------------------以下为通用不变区域-----------------------

SRC=$(wildcard $(DIR)/*.c)
OBJ=$(patsubst %.c, %.o, $(SRC))

all:$(BIN)
$(BIN):$(OBJ)
	$(CO) $@ $^ $(LFLAG)

$(DIR)/%.o:$(DIR)/%.c
	$(CC) $@ -c $< $(CFLAG)

.PHONY:clean
clean:
	rm $(OBJ) $(BIN)
